In [1]:
# To simplify the problem, we only consider the main chain and omit the side chain 
main_chain = "APRLRFY" # 7 amino acids

In [2]:
def validate_main_chain(main_chain: str):
    for amino_acid in main_chain:
        if validate_amino_acid(amino_acid) == False:
            return False
    return True


def validate_amino_acid(amino_acid: str) -> bool:
    valid_amino_acids = [
        "A",  # Alanine
        "C",  # Cysteine
        "D",  # Aspartic acid
        "E",  # Glutamic acid
        "F",  # Phenylalanine
        "G",  # Glycine
        "H",  # Histidine
        "I",  # Isoleucine
        "K",  # Lysine
        "L",  # Leucine
        "M",  # Methionine
        "N",  # Asparagine
        "P",  # Proline
        "Q",  # Glutamine
        "R",  # Arginine
        "S",  # Serine
        "T",  # Threonine
        "V",  # Valine
        "W",  # Tryptophan
        "Y",  # Tyrosine
    ]
    if amino_acid != "" and amino_acid not in valid_amino_acids:
        return False
    return True

In [3]:
validate_main_chain(main_chain)

True

In [4]:
from pathlib import Path
import os
import numpy as np
from typing import Tuple, List

def path_of_mj():
    path1 = Path().parent.absolute()
    path2 = Path("resources")
    path1 = os.path.join(path1, path2)
    filename = "mj_matrix.txt"
    path = os.path.normpath(os.path.join(path1, filename))
    return path


def load_mj_matrix() -> Tuple[np.ndarray, List[str]]:
    path = path_of_mj()
    matrix = np.loadtxt(fname=path, dtype=str)
    mj_matrix = np.zeros((np.shape(matrix)[0], np.shape(matrix)[1]))
    for row in range(1, np.shape(matrix)[0]):
        for col in range(row - 1, np.shape(matrix)[1]):
            mj_matrix[row, col] = float(matrix[row, col])
    mj_matrix = mj_matrix[1:,]
    amino_acids = list(matrix[0, :])
    return mj_matrix, amino_acids

def calculate_energy_matrix(main_chain: str) -> np.ndarray:
        chain_len = len(main_chain)
        if(validate_main_chain(main_chain) == False):
            print("The wrong string of amino acids.")
            return
        mj_matrix, list_amino_acids = load_mj_matrix() 
        energy_matrix = np.zeros((chain_len + 1, 2, chain_len + 1, 2))
        for i in range(1, chain_len + 1):
            for j in range(i + 1, chain_len + 1):
                aa_i = list_amino_acids.index(main_chain[i - 1])
                aa_j = list_amino_acids.index(main_chain[j - 1])
                energy_matrix[i, 0, j, 0] = mj_matrix[min(aa_i, aa_j), max(aa_i, aa_j)]
        return energy_matrix

In [5]:
### MJ interaction table
mj, amino_acids = load_mj_matrix()
print(amino_acids)

['C', 'M', 'F', 'I', 'L', 'V', 'W', 'Y', 'A', 'G', 'T', 'S', 'N', 'Q', 'D', 'E', 'H', 'R', 'K', 'P']


In [6]:
print(mj)

[[-5.44 -4.99 -5.8  -5.5  -5.83 -4.96 -4.95 -4.16 -3.57 -3.16 -3.11 -2.86
  -2.59 -2.85 -2.41 -2.27 -3.6  -2.57 -1.95 -3.07]
 [ 0.   -5.46 -6.56 -6.02 -6.41 -5.32 -5.55 -4.91 -3.94 -3.39 -3.51 -3.03
  -2.95 -3.3  -2.57 -2.89 -3.98 -3.12 -2.48 -3.45]
 [ 0.    0.   -7.26 -6.84 -7.28 -6.29 -6.16 -5.66 -4.81 -4.13 -4.28 -4.02
  -3.75 -4.1  -3.48 -3.56 -4.77 -3.98 -3.36 -4.25]
 [ 0.    0.    0.   -6.54 -7.04 -6.05 -5.78 -5.25 -4.58 -3.78 -4.03 -3.52
  -3.24 -3.67 -3.17 -3.27 -4.14 -3.63 -3.01 -3.76]
 [ 0.    0.    0.    0.   -7.37 -6.48 -6.14 -5.67 -4.91 -4.16 -4.34 -3.92
  -3.74 -4.04 -3.4  -3.59 -4.54 -4.03 -3.37 -4.2 ]
 [ 0.    0.    0.    0.    0.   -5.52 -5.18 -4.62 -4.04 -3.38 -3.46 -3.05
  -2.83 -3.07 -2.48 -2.67 -3.58 -3.07 -2.49 -3.32]
 [ 0.    0.    0.    0.    0.    0.   -5.06 -4.66 -3.82 -3.42 -3.22 -2.99
  -3.07 -3.11 -2.84 -2.99 -3.98 -3.41 -2.69 -3.73]
 [ 0.    0.    0.    0.    0.    0.    0.   -4.17 -3.36 -3.01 -3.01 -2.78
  -2.76 -2.97 -2.76 -2.79 -3.52 -3.16 -2.6  -3.19]


In [7]:
### Calculating energy for the special peptide
miyazawa_jernigan=calculate_energy_matrix(main_chain)
print(miyazawa_jernigan)

[[[[ 0.    0.  ]
   [ 0.    0.  ]
   [ 0.    0.  ]
   [ 0.    0.  ]
   [ 0.    0.  ]
   [ 0.    0.  ]
   [ 0.    0.  ]
   [ 0.    0.  ]]

  [[ 0.    0.  ]
   [ 0.    0.  ]
   [ 0.    0.  ]
   [ 0.    0.  ]
   [ 0.    0.  ]
   [ 0.    0.  ]
   [ 0.    0.  ]
   [ 0.    0.  ]]]


 [[[ 0.    0.  ]
   [ 0.    0.  ]
   [-2.03  0.  ]
   [-1.83  0.  ]
   [-4.91  0.  ]
   [-1.83  0.  ]
   [-4.81  0.  ]
   [-3.36  0.  ]]

  [[ 0.    0.  ]
   [ 0.    0.  ]
   [ 0.    0.  ]
   [ 0.    0.  ]
   [ 0.    0.  ]
   [ 0.    0.  ]
   [ 0.    0.  ]
   [ 0.    0.  ]]]


 [[[ 0.    0.  ]
   [ 0.    0.  ]
   [ 0.    0.  ]
   [-1.7   0.  ]
   [-4.2   0.  ]
   [-1.7   0.  ]
   [-4.25  0.  ]
   [-3.19  0.  ]]

  [[ 0.    0.  ]
   [ 0.    0.  ]
   [ 0.    0.  ]
   [ 0.    0.  ]
   [ 0.    0.  ]
   [ 0.    0.  ]
   [ 0.    0.  ]
   [ 0.    0.  ]]]


 [[[ 0.    0.  ]
   [ 0.    0.  ]
   [ 0.    0.  ]
   [ 0.    0.  ]
   [-4.03  0.  ]
   [-1.55  0.  ]
   [-3.98  0.  ]
   [-3.16  0.  ]]

  [[ 0.    0.  ]
   [ 0.    

In [8]:
def calculate_energy_matrix_2(main_chain: str) -> np.ndarray:
        chain_len = len(main_chain)
        if(validate_main_chain(main_chain) == False):
            print("The wrong string of amino acids.")
            return
        mj_matrix, list_amino_acids = load_mj_matrix() 
        energy_matrix = np.zeros((chain_len + 1, chain_len + 1)) ###
        for i in range(1, chain_len + 1):
            for j in range(i + 1, chain_len + 1):
                aa_i = list_amino_acids.index(main_chain[i - 1])
                aa_j = list_amino_acids.index(main_chain[j - 1])
                energy_matrix[i, j] = mj_matrix[min(aa_i, aa_j), max(aa_i, aa_j)] ###
        return energy_matrix

In [9]:
### Calculating energy for the special peptide
miyazawa_jernigan_2=calculate_energy_matrix_2(main_chain)
print(miyazawa_jernigan_2)

[[ 0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.   -2.03 -1.83 -4.91 -1.83 -4.81 -3.36]
 [ 0.    0.    0.   -1.7  -4.2  -1.7  -4.25 -3.19]
 [ 0.    0.    0.    0.   -4.03 -1.55 -3.98 -3.16]
 [ 0.    0.    0.    0.    0.   -4.03 -7.28 -5.67]
 [ 0.    0.    0.    0.    0.    0.   -3.98 -3.16]
 [ 0.    0.    0.    0.    0.    0.    0.   -5.66]
 [ 0.    0.    0.    0.    0.    0.    0.    0.  ]]
